// Catalog metadata captured read-only from the user-owned engine; game-profile bound.
#pragma once
struct VariantMeta {const char* hero;int skin;const char* model;int gear;const char* name;const char* gear_name;};
constexpr VariantMeta variants[]={
{"Ahri",86,"Ahri",0,"联盟不朽 阿狸","天选"},
{"Ahri",86,"Ahri",1,"联盟不朽 阿狸","不朽"},
{"Ahri",86,"Ahri",2,"联盟不朽 阿狸","大魔王形态"},
{"Ashe",76,"Ashe",0,"灵魂莲华 艾希","Level 1"},
{"Ashe",76,"Ashe",1,"灵魂莲华 艾希","Level 2"},
{"Ashe",76,"Ashe",2,"灵魂莲华 艾希","Level 3"},
{"Ashe",77,"Ashe",0,"灵魂莲华 艾希 流火","Level 1"},
{"Ashe",77,"Ashe",1,"灵魂莲华 艾希 流火","Level 2"},
{"Ashe",77,"Ashe",2,"灵魂莲华 艾希 流火","Level 3"},
{"Ashe",78,"Ashe",0,"灵魂莲华 艾希 风起","Level 1"},
{"Ashe",78,"Ashe",1,"灵魂莲华 艾希 风起","Level 2"},
{"Ashe",78,"Ashe",2,"灵魂莲华 艾希 风起","Level 3"},
{"Ashe",79,"Ashe",0,"灵魂莲华 艾希 雁来","Level 1"},
{"Ashe",79,"Ashe",1,"灵魂莲华 艾希 雁来","Level 2"},
{"Ashe",79,"Ashe",2,"灵魂莲华 艾希 雁来","Level 3"},
{"Ashe",80,"Ashe",0,"灵魂莲华 艾希 雪落","Level 1"},
{"Ashe",80,"Ashe",1,"灵魂莲华 艾希 雪落","Level 2"},
{"Ashe",80,"Ashe",2,"灵魂莲华 艾希 雪落","Level 3"},
{"Ashe",81,"Ashe",0,"灵魂莲华 艾希 月升","Level 1"},
{"Ashe",81,"Ashe",1,"灵魂莲华 艾希 月升","Level 2"},
{"Ashe",81,"Ashe",2,"灵魂莲华 艾希 月升","Level 3"},
{"Ashe",82,"Ashe",0,"灵魂莲华 艾希 朝花","Level 1"},
{"Ashe",82,"Ashe",1,"灵魂莲华 艾希 朝花","Level 2"},
{"Ashe",82,"Ashe",2,"灵魂莲华 艾希 朝花","Level 3"},
{"Ashe",83,"Ashe",0,"神龙尊者 苍龙艾希 至强","Level 1"},
{"Ashe",83,"Ashe",1,"神龙尊者 苍龙艾希 至强","Level 2"},
{"Ashe",83,"Ashe",2,"神龙尊者 苍龙艾希 至强","Level 3"},
{"Caitlyn",22,"Caitlyn",0,"战斗学院 凯特琳","未来 Level 1 "},
{"Caitlyn",22,"Caitlyn",1,"战斗学院 凯特琳","未来 Level 2"},
{"Caitlyn",22,"Caitlyn",2,"战斗学院 凯特琳","未来 Level 3"},
{"Caitlyn",23,"Caitlyn",0,"战斗学院 凯特琳 不死鸟","未来 Level 1 "},
{"Caitlyn",23,"Caitlyn",1,"战斗学院 凯特琳 不死鸟","未来 Level 2"},
{"Caitlyn",23,"Caitlyn",2,"战斗学院 凯特琳 不死鸟","未来 Level 3"},
{"Caitlyn",24,"Caitlyn",0,"战斗学院 凯特琳 天马","未来 Level 1 "},
{"Caitlyn",24,"Caitlyn",1,"战斗学院 凯特琳 天马","未来 Level 2"},
{"Caitlyn",24,"Caitlyn",2,"战斗学院 凯特琳 天马","未来 Level 3"},
{"Caitlyn",25,"Caitlyn",0,"战斗学院 凯特琳 独角兽","未来 Level 1 "},
{"Caitlyn",25,"Caitlyn",1,"战斗学院 凯特琳 独角兽","未来 Level 2"},
{"Caitlyn",25,"Caitlyn",2,"战斗学院 凯特琳 独角兽","未来 Level 3"},
{"Caitlyn",26,"Caitlyn",0,"战斗学院 凯特琳 黑龙","未来 Level 1 "},
{"Caitlyn",26,"Caitlyn",1,"战斗学院 凯特琳 黑龙","未来 Level 2"},
{"Caitlyn",26,"Caitlyn",2,"战斗学院 凯特琳 黑龙","未来 Level 3"},
{"Caitlyn",27,"Caitlyn",0,"战斗学院 凯特琳 狮鹫","未来 Level 1 "},
{"Caitlyn",27,"Caitlyn",1,"战斗学院 凯特琳 狮鹫","未来 Level 2"},
{"Caitlyn",27,"Caitlyn",2,"战斗学院 凯特琳 狮鹫","未来 Level 3"},
{"Caitlyn",28,"Caitlyn",0,"双城之战 凯特琳","未来 Level 1 "},
{"Caitlyn",28,"Caitlyn",1,"双城之战 凯特琳","未来 Level 2"},
{"Caitlyn",28,"Caitlyn",2,"双城之战 凯特琳","未来 Level 3"},
{"Ezreal",5,"Ezreal",0,"未来战士 伊泽瑞尔","未来战士: Level 1"},
{"Ezreal",5,"Ezreal",1,"未来战士 伊泽瑞尔","未来战士: Level 2"},
{"Ezreal",5,"Ezreal",2,"未来战士 伊泽瑞尔","未来战士: Level 3"},
{"Jinx",60,"Jinx",0,"双城之战2 破碎者 金克丝","头号通缉犯"},
{"Jinx",60,"Jinx",1,"双城之战2 破碎者 金克丝","爆爆形态"},
{"Jinx",60,"Jinx",2,"双城之战2 破碎者 金克丝","底城英雄"},
{"Kaisa",71,"Kaisa",0,"联盟不朽 卡莎","基础形态"},
{"Kaisa",71,"Kaisa",1,"联盟不朽 卡莎","高级形态"},
{"Kaisa",71,"Kaisa",2,"联盟不朽 卡莎","特级形态"},
{"Katarina",29,"Katarina",0,"女帝 卡特琳娜","女帝: 英勇匕首"},
{"Katarina",29,"Katarina",1,"女帝 卡特琳娜","女帝: 果决匕首"},
{"Katarina",29,"Katarina",2,"女帝 卡特琳娜","女帝: 无我匕首"},
{"Katarina",29,"Katarina",3,"女帝 卡特琳娜","女帝: 飒爽匕首"},
{"Katarina",29,"Katarina",4,"女帝 卡特琳娜","女帝: 敏锐匕首"},
{"Katarina",29,"Katarina",5,"女帝 卡特琳娜","女帝: 深谋匕首"},
{"Katarina",30,"Katarina",0,"女帝 卡特琳娜 纹章之刻印·英勇","女帝: 英勇匕首"},
{"Katarina",30,"Katarina",1,"女帝 卡特琳娜 纹章之刻印·英勇","女帝: 果决匕首"},
{"Katarina",30,"Katarina",2,"女帝 卡特琳娜 纹章之刻印·英勇","女帝: 无我匕首"},
{"Katarina",30,"Katarina",3,"女帝 卡特琳娜 纹章之刻印·英勇","女帝: 飒爽匕首"},
{"Katarina",30,"Katarina",4,"女帝 卡特琳娜 纹章之刻印·英勇","女帝: 敏锐匕首"},
{"Katarina",30,"Katarina",5,"女帝 卡特琳娜 纹章之刻印·英勇","女帝: 深谋匕首"},
{"Katarina",31,"Katarina",0,"女帝 卡特琳娜 纹章之刻印·果决","女帝: 英勇匕首"},
{"Katarina",31,"Katarina",1,"女帝 卡特琳娜 纹章之刻印·果决","女帝: 果决匕首"},
{"Katarina",31,"Katarina",2,"女帝 卡特琳娜 纹章之刻印·果决","女帝: 无我匕首"},
{"Katarina",31,"Katarina",3,"女帝 卡特琳娜 纹章之刻印·果决","女帝: 飒爽匕首"},
{"Katarina",31,"Katarina",4,"女帝 卡特琳娜 纹章之刻印·果决","女帝: 敏锐匕首"},
{"Katarina",31,"Katarina",5,"女帝 卡特琳娜 纹章之刻印·果决","女帝: 深谋匕首"},
{"Katarina",32,"Katarina",0,"女帝 卡特琳娜 纹章之刻印·无我","女帝: 英勇匕首"},
{"Katarina",32,"Katarina",1,"女帝 卡特琳娜 纹章之刻印·无我","女帝: 果决匕首"},
{"Katarina",32,"Katarina",2,"女帝 卡特琳娜 纹章之刻印·无我","女帝: 无我匕首"},
{"Katarina",32,"Katarina",3,"女帝 卡特琳娜 纹章之刻印·无我","女帝: 飒爽匕首"},
{"Katarina",32,"Katarina",4,"女帝 卡特琳娜 纹章之刻印·无我","女帝: 敏锐匕首"},
{"Katarina",32,"Katarina",5,"女帝 卡特琳娜 纹章之刻印·无我","女帝: 深谋匕首"},
{"Katarina",33,"Katarina",0,"女帝 卡特琳娜 纹章之刻印·飒爽","女帝: 英勇匕首"},
{"Katarina",33,"Katarina",1,"女帝 卡特琳娜 纹章之刻印·飒爽","女帝: 果决匕首"},
{"Katarina",33,"Katarina",2,"女帝 卡特琳娜 纹章之刻印·飒爽","女帝: 无我匕首"},
{"Katarina",33,"Katarina",3,"女帝 卡特琳娜 纹章之刻印·飒爽","女帝: 飒爽匕首"},
{"Katarina",33,"Katarina",4,"女帝 卡特琳娜 纹章之刻印·飒爽","女帝: 敏锐匕首"},
{"Katarina",33,"Katarina",5,"女帝 卡特琳娜 纹章之刻印·飒爽","女帝: 深谋匕首"},
{"Katarina",34,"Katarina",0,"女帝 卡特琳娜 纹章之刻印·敏锐","女帝: 英勇匕首"},
{"Katarina",34,"Katarina",1,"女帝 卡特琳娜 纹章之刻印·敏锐","女帝: 果决匕首"},
{"Katarina",34,"Katarina",2,"女帝 卡特琳娜 纹章之刻印·敏锐","女帝: 无我匕首"},
{"Katarina",34,"Katarina",3,"女帝 卡特琳娜 纹章之刻印·敏锐","女帝: 飒爽匕首"},
{"Katarina",34,"Katarina",4,"女帝 卡特琳娜 纹章之刻印·敏锐","女帝: 敏锐匕首"},
{"Katarina",34,"Katarina",5,"女帝 卡特琳娜 纹章之刻印·敏锐","女帝: 深谋匕首"},
{"Katarina",35,"Katarina",0,"女帝 卡特琳娜 纹章之刻印·深谋","女帝: 英勇匕首"},
{"Katarina",35,"Katarina",1,"女帝 卡特琳娜 纹章之刻印·深谋","女帝: 果决匕首"},
{"Katarina",35,"Katarina",2,"女帝 卡特琳娜 纹章之刻印·深谋","女帝: 无我匕首"},
{"Katarina",35,"Katarina",3,"女帝 卡特琳娜 纹章之刻印·深谋","女帝: 飒爽匕首"},
{"Katarina",35,"Katarina",4,"女帝 卡特琳娜 纹章之刻印·深谋","女帝: 敏锐匕首"},
{"Katarina",35,"Katarina",5,"女帝 卡特琳娜 纹章之刻印·深谋","女帝: 深谋匕首"},
{"Katarina",36,"Katarina",0,"女帝 卡特琳娜 纹章·神圣加冕礼","女帝: 英勇匕首"},
{"Katarina",36,"Katarina",1,"女帝 卡特琳娜 纹章·神圣加冕礼","女帝: 果决匕首"},
{"Katarina",36,"Katarina",2,"女帝 卡特琳娜 纹章·神圣加冕礼","女帝: 无我匕首"},
{"Katarina",36,"Katarina",3,"女帝 卡特琳娜 纹章·神圣加冕礼","女帝: 飒爽匕首"},
{"Katarina",36,"Katarina",4,"女帝 卡特琳娜 纹章·神圣加冕礼","女帝: 敏锐匕首"},
{"Katarina",36,"Katarina",5,"女帝 卡特琳娜 纹章·神圣加冕礼","女帝: 深谋匕首"},
{"Kayle",6,"Kayle",0,"钢铁之翼 凯尔","钢铁: 炽诚"},
{"Kayle",6,"Kayle",1,"钢铁之翼 凯尔","钢铁: 升腾"},
{"Kayle",6,"Kayle",2,"钢铁之翼 凯尔","钢铁: 超然"},
{"Lux",7,"LuxAir",-1,"大元素使 气",""},
{"Lux",7,"LuxDark",-1,"大元素使 暗",""},
{"Lux",7,"LuxFire",-1,"大元素使 火",""},
{"Lux",7,"LuxIce",-1,"大元素使 冰",""},
{"Lux",7,"LuxMagma",-1,"大元素使 炎",""},
{"Lux",7,"LuxMystic",-1,"大元素使 神秘",""},
{"Lux",7,"LuxNature",-1,"大元素使 自然",""},
{"Lux",7,"LuxStorm",-1,"大元素使 风暴",""},
{"Lux",7,"LuxWater",-1,"大元素使 水",""},
{"MasterYi",116,"MasterYi",0,"源计划：改 · 林 易","Level 1"},
{"MissFortune",16,"MissFortune",0,"武装战姬 厄运小姐","武装战姬: 血色 "},
{"MissFortune",16,"MissFortune",1,"武装战姬 厄运小姐","武装战姬: 总攻"},
{"MissFortune",16,"MissFortune",2,"武装战姬 厄运小姐","武装战姬: 皇家"},
{"MissFortune",16,"MissFortune",3,"武装战姬 厄运小姐","武装战姬: 星辰"},
{"MissFortune",69,"MissFortune",0,"MVP T1 厄运小姐","Level 1"},
{"MissFortune",69,"MissFortune",1,"MVP T1 厄运小姐","Level 2"},
{"MissFortune",69,"MissFortune",2,"MVP T1 厄运小姐","Level 3"},
{"MissFortune",70,"MissFortune",0,"MVP T1 厄运小姐 精锐","Level 1"},
{"MissFortune",70,"MissFortune",1,"MVP T1 厄运小姐 精锐","Level 2"},
{"MissFortune",70,"MissFortune",2,"MVP T1 厄运小姐 精锐","Level 3"},
{"MissFortune",71,"MissFortune",0,"MVP T1 厄运小姐 混合的世界","Level 1"},
{"MissFortune",71,"MissFortune",1,"MVP T1 厄运小姐 混合的世界","Level 2"},
{"MissFortune",71,"MissFortune",2,"MVP T1 厄运小姐 混合的世界","Level 3"},
{"MissFortune",72,"MissFortune",0,"MVP T1 厄运小姐 决战在即","Level 1"},
{"MissFortune",72,"MissFortune",1,"MVP T1 厄运小姐 决战在即","Level 2"},
{"MissFortune",72,"MissFortune",2,"MVP T1 厄运小姐 决战在即","Level 3"},
{"MissFortune",73,"MissFortune",0,"MVP T1 厄运小姐 燃","Level 1"},
{"MissFortune",73,"MissFortune",1,"MVP T1 厄运小姐 燃","Level 2"},
{"MissFortune",73,"MissFortune",2,"MVP T1 厄运小姐 燃","Level 3"},
{"MissFortune",74,"MissFortune",0,"MVP T1 厄运小姐 登神","Level 1"},
{"MissFortune",74,"MissFortune",1,"MVP T1 厄运小姐 登神","Level 2"},
{"MissFortune",74,"MissFortune",2,"MVP T1 厄运小姐 登神","Level 3"},
{"MissFortune",75,"MissFortune",0,"MVP T1 厄运小姐 王冠之重","Level 1"},
{"MissFortune",75,"MissFortune",1,"MVP T1 厄运小姐 王冠之重","Level 2"},
{"MissFortune",75,"MissFortune",2,"MVP T1 厄运小姐 王冠之重","Level 3"},
{"Mordekaiser",54,"Mordekaiser",0,"萨恩 · 乌祖尔 莫德凯撒","基础形态"},
{"Mordekaiser",54,"Mordekaiser",1,"萨恩 · 乌祖尔 莫德凯撒","高级形态"},
{"Mordekaiser",54,"Mordekaiser",2,"萨恩 · 乌祖尔 莫德凯撒","特级形态"},
{"Morgana",80,"Morgana",0,"灵魂莲华 莫甘娜","Level 1"},
{"Renekton",26,"Renekton",0,"源计划：泯灭 雷克顿","源计划: 泯灭off"},
{"Renekton",26,"Renekton",1,"源计划：泯灭 雷克顿","源计划: 泯灭on"},
{"Renekton",26,"Renekton",2,"源计划：泯灭 雷克顿","源计划: 泯灭Fins"},
{"Renekton",26,"Renekton",3,"源计划：泯灭 雷克顿","源计划: 泯灭终极"},
{"Renekton",27,"Renekton",0,"源计划：泯灭 雷克顿 裂变","源计划: 泯灭off"},
{"Renekton",27,"Renekton",1,"源计划：泯灭 雷克顿 裂变","源计划: 泯灭on"},
{"Renekton",27,"Renekton",2,"源计划：泯灭 雷克顿 裂变","源计划: 泯灭Fins"},
{"Renekton",27,"Renekton",3,"源计划：泯灭 雷克顿 裂变","源计划: 泯灭终极"},
{"Renekton",28,"Renekton",0,"源计划：泯灭 雷克顿 地覆","源计划: 泯灭off"},
{"Renekton",28,"Renekton",1,"源计划：泯灭 雷克顿 地覆","源计划: 泯灭on"},
{"Renekton",28,"Renekton",2,"源计划：泯灭 雷克顿 地覆","源计划: 泯灭Fins"},
{"Renekton",28,"Renekton",3,"源计划：泯灭 雷克顿 地覆","源计划: 泯灭终极"},
{"Renekton",29,"Renekton",0,"源计划：泯灭 雷克顿 默化","源计划: 泯灭off"},
{"Renekton",29,"Renekton",1,"源计划：泯灭 雷克顿 默化","源计划: 泯灭on"},
{"Renekton",29,"Renekton",2,"源计划：泯灭 雷克顿 默化","源计划: 泯灭Fins"},
{"Renekton",29,"Renekton",3,"源计划：泯灭 雷克顿 默化","源计划: 泯灭终极"},
{"Renekton",30,"Renekton",0,"源计划：泯灭 雷克顿 失控","源计划: 泯灭off"},
{"Renekton",30,"Renekton",1,"源计划：泯灭 雷克顿 失控","源计划: 泯灭on"},
{"Renekton",30,"Renekton",2,"源计划：泯灭 雷克顿 失控","源计划: 泯灭Fins"},
{"Renekton",30,"Renekton",3,"源计划：泯灭 雷克顿 失控","源计划: 泯灭终极"},
{"Renekton",31,"Renekton",0,"源计划：泯灭 雷克顿 惩戒","源计划: 泯灭off"},
{"Renekton",31,"Renekton",1,"源计划：泯灭 雷克顿 惩戒","源计划: 泯灭on"},
{"Renekton",31,"Renekton",2,"源计划：泯灭 雷克顿 惩戒","源计划: 泯灭Fins"},
{"Renekton",31,"Renekton",3,"源计划：泯灭 雷克顿 惩戒","源计划: 泯灭终极"},
{"Renekton",32,"Renekton",0,"源计划：泯灭 雷克顿 震击","源计划: 泯灭off"},
{"Renekton",32,"Renekton",1,"源计划：泯灭 雷克顿 震击","源计划: 泯灭on"},
{"Renekton",32,"Renekton",2,"源计划：泯灭 雷克顿 震击","源计划: 泯灭Fins"},
{"Renekton",32,"Renekton",3,"源计划：泯灭 雷克顿 震击","源计划: 泯灭终极"},
{"Sett",66,"Sett",0,"金蛇巨星 瑟提","基础形态"},
{"Sett",66,"Sett",1,"金蛇巨星 瑟提","天神形态"},
{"Sett",66,"Sett",2,"金蛇巨星 瑟提","蛇灵形态"},
{"Sona",6,"SonaDJGenre02",-1,"DJ 震荡",""},
{"Sona",6,"SonaDJGenre03",-1,"DJ 空灵",""},
{"Viego",43,"Viego",0,"王 佛耶戈","Level 1"},
{"Viego",43,"Viego",1,"王 佛耶戈","Level 2"},
{"Viego",43,"Viego",2,"王 佛耶戈","Level 3"},
{"Viego",43,"Viego",3,"王 佛耶戈","Level 4"},
{"Viego",43,"Viego",4,"王 佛耶戈","Level 5"},
{"Viego",43,"Viego",5,"王 佛耶戈","Level 6"},
{"Viego",43,"Viego",6,"王 佛耶戈","Level 7"},
};
